title: Polychromatic
author: Luke Horwell
email: code@horwell.me
description: >-
  Polychromatic, an RGB lighting management front-end application for GNU/Linux.
  Supports OpenRazer, and more brands in future.

baseurl: ""
url: "https://polychromatic.app"
source_code_url: "https://github.com/polychromatic"

# Build settings
markdown: kramdown
disable_disk_cache: true

#~ plugins:
#~  - jekyll-feed

# Exclude from processing.
exclude:
  - vendor/
  - scripts/
  - LICENSE
  - README.md

# Common URLs
openrazer_repo: "https://github.com/openrazer/openrazer/"
openrazer_website: "https://openrazer.github.io/"
polychromatic_org: "https://github.com/polychromatic/"
polychromatic_repo: "https://github.com/polychromatic/polychromatic/"
rss_feed: "https://github.com/polychromatic/polychromatic/releases.atom"
twitter: "polychromic_app"
